Repository usablica/intro.js, pull requests merged in 2020-11, with the labels that each got.

#1055 add buttonClass to docs
  docs/docs/intro/options.md
Labels: wontfix

#1047 Add additional class option for progressbar
  src/core/showElement.js
  src/index.js
Labels: wontfix

#1074 fix(intro): adding hasAttribute
  src/core/introForElement.js
Labels: bug fix

#1088 feat: adding `title` field to intro items
  example/RTL/index.html
  example/hello-world/index.html
  src/core/hint.js
  src/core/introForElement.js
  src/core/placeTooltip.js
  src/core/refresh.js
  src/core/showElement.js
  src/index.js
  src/styles/introjs-rtl.scss
  src/styles/introjs.scss
Labels: enhancement, new feature

#1092 fix(babel): updating the browser support
  .babelrc
  README.md
  babel.config.js
  bower.json
  component.json
  package.json
  src/core/introForElement.js
Labels: bug fix, enhancement
